"use client";

import { Check, Clipboard, Mail, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { z } from "zod";

const schema=z.object({name:z.string().min(2,"Please enter your name."),email:z.string().email("Enter a valid email address."),company:z.string().optional(),subject:z.string().min(3,"Please add a subject."),message:z.string().min(20,"Please share a little more detail (20 characters minimum).")});
type Fields=z.infer<typeof schema>;
export default function ContactForm({email}:{email:string}){const [errors,setErrors]=useState<Record<string,string>>({});const [sent,setSent]=useState(false);const [copied,setCopied]=useState(false);if(!email)return <div className="resume-viewer"><div><Mail size={28}/><h2>Email setup pending</h2><p className="muted">Add <code>CONTACT_EMAIL</code> to the deployment environment. GitHub and LinkedIn remain available below.</p></div></div>;const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const data=Object.fromEntries(form) as Fields;const result=schema.safeParse(data);if(!result.success){setErrors(Object.fromEntries(result.error.issues.map(i=>[String(i.path[0]),i.message])));return}setErrors({});const body=`Hi Manish,\n\n${result.data.message}\n\nFrom: ${result.data.name} (${result.data.email})${result.data.company?`\nCompany: ${result.data.company}`:""}`;window.location.href=`mailto:${email}?subject=${encodeURIComponent(result.data.subject)}&body=${encodeURIComponent(body)}`;setSent(true)};return <><form onSubmit={submit} noValidate><div className="form-grid">{([['name','Name'],['email','Email'],['company','Company'],['subject','Subject']] as const).map(([name,label])=><div className="field" key={name}><label htmlFor={name}>{label}</label><input id={name} name={name} type={name==='email'?'email':'text'} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<span id={`${name}-error`} className="field-error">{errors[name]}</span>}</div>)}<div className="field full"><label htmlFor="message">Message</label><textarea id="message" name="message" aria-invalid={!!errors.message}/>{errors.message&&<span className="field-error">{errors.message}</span>}</div></div><div className="actions" style={{marginTop:30}}><button className="button button-primary" type="submit"><Send size={15}/> Open email client</button><button className="button" type="button" onClick={()=>navigator.clipboard.writeText(email).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1600)})}>{copied?<Check size={15}/>:<Clipboard size={15}/>} {copied?'Copied':'Copy email'}</button></div>{sent&&<p role="status" style={{color:"var(--green)"}}>Your email client should now be open with the message prefilled.</p>}</form></>}
